pipeline {
	
	agent any
	
	tools {
        jdk 'java21'
        maven 'maven'
    }
	
	stages{
		
		stage('Checkout') {
			
			steps {
				checkout scm
			}
			
		}
		
		stage('Build and Test') {
			steps {
				dir('cicd/CICD') {
					sh 'mvn clean test package'
				}
				
			}
		}
		
		stage('UI Tests (Selenium)') {
    		when {
        		expression { return params.RUN_UI_TESTS }
    		}	
    		steps {
				dir('cicd/CICD') {
        			sh 'mvn -B verify -DskipUnitTests=true'
        		}
    		}
		}
		
		
	}
	
	post {
		always {
			junit 'cicd/CICD/target/surefire-reports/*.xml'
		}
	}
	
}