pipeline {
	
	agent any
	
	stages {
		
		tools {
        	jdk 'jdk-17'
	        maven 'maven-3.9.0'
    	}
		
		stage('Checkout') {
			
			steps {
				checkout scm
			}
			
		}
		
		stage('Build and Test') {
			steps {
				dir('cicd/CICD') {
					sh 'mvn clean test package'
				}
				
			}
		}
		
	}
	
}